site_name: Edith Docs
theme:
  name: material
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.tracking
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
repo_name: Edith
repo_url: https://github.com/NeilDevelopment/Edith
copyright: Copyright &copy; 2021 - 2022 Neil Development
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NeilDevelopment
